development:
  telegram:
    bot:
      token: <%= ENV['BOT_TOKEN'] %>
      username: '@amrsbot'

test:
  telegram:
    bot:
      token: <%= ENV['BOT_TOKEN'] %>
      username: '@amrsbot'

production:
  telegram:
    bot:
      token: <%= ENV['BOT_TOKEN'] %>
      username: '@amrsbot'
